export const ATLASSIAN_API_LOADING = "ATLASSIAN_API_LOADING";

export const GET_BOARDS_OK = "GET_BOARDS_OK";
export const GET_BOARDS_ERROR = "GET_BOARDS_ERROR";

export const SET_SPRINT_ID = "SET_SPRINT_ID";
export const GET_SPRINTS_OK = "GET_SPRINTS_OK";
export const GET_SPRINTS_ERROR = "GET_SPRINTS_ERROR";

export const GET_JQL_OK = "GET_JQL_OK";
export const GET_JQL_ERROR = "GET_JQL_OK";